object Versions {
    const val hilt = "2.46.1"
    const val okHttp = "5.0.0-alpha.7"
    const val retrofit = "2.9.0"
    const val room = "2.5.2"
    const val viewModel = "2.6.2"
    const val navigation = "2.7.4"
    const val circleImage = "3.1.0"
    const val shimmer = "0.5.0"
    const val glide = "4.15.0"
    const val datastore = "1.0.0"
    const val viewpager2 = "1.0.0"
    const val paging = "3.2.1"
    const val roomPaging = "2.6.0-rc01"
    const val swipeRefresh = "1.1.0"
    const val camerax = "1.4.0-alpha01"
    const val dotIndicator = "4.3"
    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val expresoCore = "3.5.1"
}